name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy project files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "~/compliant-tracker"

      - name: Run commands on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/compliant-tracker
            sudo docker build -t complaint-tracker .
            # Stop and remove any old containers on port 5000
            sudo docker stop $(sudo docker ps -q --filter "publish=5000") || true
            sudo docker rm $(sudo docker ps -aq --filter "publish=5000") || true
            # Run the new one
            sudo docker run -d -p 5000:5000 complaint-tracker
